
export const MOCK_MOVIES: any[] = [
  {
    id: 'mock-pk-1',
    title: 'The Legend of Maula Jatt',
    backdrop_path: 'https://images.unsplash.com/photo-1594908900066-3f47337549d8?auto=format&fit=crop&q=80&w=1920',
    poster_path: 'https://images.unsplash.com/photo-1594908900066-3f47337549d8?auto=format&fit=crop&q=80&w=500',
    overview: 'Maula Jatt, a fierce prizefighter with a tortured past seeks vengeance against his arch nemesis Noori Natt.',
    vote_average: 8.9,
    release_date: '2022-10-13',
    media_type: 'movie' as const,
    category: 'Pakistani',
    views: 5200000,
    trendingScore: 99,
    region: 'Pakistani'
  },
  {
    id: 'mock-pk-2',
    title: 'Parizaad',
    backdrop_path: 'https://images.unsplash.com/photo-1626814026160-2237a95fc5a0?auto=format&fit=crop&q=80&w=1920',
    poster_path: 'https://images.unsplash.com/photo-1626814026160-2237a95fc5a0?auto=format&fit=crop&q=80&w=500',
    overview: 'The journey of a simple man with a golden heart who faces challenges due to his appearance.',
    vote_average: 9.7,
    release_date: '2021-07-20',
    media_type: 'tv' as const,
    category: 'Pakistani',
    views: 8500000,
    trendingScore: 95,
    region: 'Pakistani'
  },
  {
    id: 'mock-pk-3',
    title: 'Zindagi Gulzar Hai',
    backdrop_path: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&q=80&w=1920',
    poster_path: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&q=80&w=500',
    overview: 'A story of two people with contrasting perspectives on life who find love.',
    vote_average: 9.4,
    release_date: '2012-11-30',
    media_type: 'tv' as const,
    category: 'Pakistani',
    views: 4100000,
    trendingScore: 88,
    region: 'Pakistani'
  },
  {
    id: 'mock-we-1',
    title: 'Oppenheimer',
    backdrop_path: 'https://images.unsplash.com/photo-1440404653325-ab127d49abc1?auto=format&fit=crop&q=80&w=1920',
    poster_path: 'https://images.unsplash.com/photo-1440404653325-ab127d49abc1?auto=format&fit=crop&q=80&w=500',
    overview: 'The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb.',
    vote_average: 8.6,
    release_date: '2023-07-21',
    media_type: 'movie' as const,
    category: 'Western',
    views: 12000000,
    trendingScore: 97,
    isTrendingNow: true
  },
  {
    id: 'mock-we-2',
    title: 'Stranger Things',
    backdrop_path: 'https://images.unsplash.com/photo-1626814026160-2237a95fc5a0?auto=format&fit=crop&q=80&w=1920',
    poster_path: 'https://images.unsplash.com/photo-1626814026160-2237a95fc5a0?auto=format&fit=crop&q=80&w=500',
    overview: 'When a young boy vanishes, a small town uncovers a mystery involving secret experiments and terrifying supernatural forces.',
    vote_average: 8.7,
    release_date: '2016-07-15',
    media_type: 'tv' as const,
    category: 'Western',
    views: 45000000,
    trendingScore: 94,
    isTrendingNow: true
  },
  {
    id: 'mock-we-3',
    title: 'The Dark Knight',
    backdrop_path: 'https://images.unsplash.com/photo-1478720568477-152d9b164e26?auto=format&fit=crop&q=80&w=1920',
    poster_path: 'https://images.unsplash.com/photo-1478720568477-152d9b164e26?auto=format&fit=crop&q=80&w=500',
    overview: 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.',
    vote_average: 9.0,
    release_date: '2008-07-18',
    media_type: 'movie' as const,
    category: 'Western',
    views: 24000000,
    trendingScore: 92
  },
  {
    id: 'mock-1',
    title: 'Home Genesis',
    backdrop_path: 'https://picsum.photos/seed/genesis/1920/1080',
    poster_path: 'https://picsum.photos/seed/genesis-p/500/750',
    overview: 'In a world where consciousness is digital, one ghost in the machine seeks the truth of its origin.',
    vote_average: 9.8,
    release_date: '2026-04-12',
    media_type: 'movie' as const,
    category: 'Trending',
    views: 1250000,
    trendingScore: 98
  },
  {
    id: 'mock-2',
    title: 'Synthetic Dreams',
    backdrop_path: 'https://picsum.photos/seed/dreams/1920/1080',
    poster_path: 'https://picsum.photos/seed/dreams-p/500/750',
    overview: 'A journey through the neon-lit corridors of a future that never was.',
    vote_average: 9.5,
    release_date: '2025-11-20',
    media_type: 'movie' as const,
    category: 'Action',
    views: 850000,
    trendingScore: 92
  },
  {
    id: 'mock-3',
    title: 'The Last Protocol',
    backdrop_path: 'https://picsum.photos/seed/protocol/1920/1080',
    poster_path: 'https://picsum.photos/seed/protocol-p/500/750',
    overview: 'When the final server shuts down, what remains of humanity?',
    vote_average: 9.2,
    release_date: '2026-01-05',
    media_type: 'tv' as const,
    category: 'Sci-Fi',
    views: 2100000,
    trendingScore: 85
  },
  {
    id: 'mock-4',
    title: 'Neon Nights',
    backdrop_path: 'https://picsum.photos/seed/neon/1920/1080',
    poster_path: 'https://picsum.photos/seed/neon-p/500/750',
    overview: 'The city never sleeps, and neither do the shadows that haunt its streets.',
    vote_average: 8.9,
    release_date: '2024-08-15',
    media_type: 'movie' as const,
    category: 'Trending',
    views: 450000,
    trendingScore: 78
  },
  {
    id: 'mock-5',
    title: 'Cyber Soul',
    backdrop_path: 'https://picsum.photos/seed/soul/1920/1080',
    poster_path: 'https://picsum.photos/seed/soul-p/500/750',
    overview: 'Can a machine feel love? A roboticist risks everything to find out.',
    vote_average: 9.4,
    release_date: '2026-03-30',
    media_type: 'movie' as const,
    category: 'Romance',
    views: 1800000,
    trendingScore: 96
  },
  {
    id: 'mock-6',
    title: 'Void Walker',
    backdrop_path: 'https://picsum.photos/seed/void/1920/1080',
    poster_path: 'https://picsum.photos/seed/void-p/500/750',
    overview: 'A nomadic explorer discovers an ancient rift in the fabric of space.',
    vote_average: 8.7,
    release_date: '2026-02-15',
    media_type: 'movie' as const,
    category: 'Sci-Fi',
    views: 3200000,
    trendingScore: 90
  },
  {
    id: 'mock-7',
    title: 'Digital Hearts',
    backdrop_path: 'https://picsum.photos/seed/hearts/1920/1080',
    poster_path: 'https://picsum.photos/seed/hearts-p/500/750',
    overview: 'A romantic tale set in a virtual reality metropolis.',
    vote_average: 8.4,
    release_date: '2025-12-25',
    media_type: 'movie' as const,
    category: 'Romance',
    views: 600000,
    trendingScore: 75
  },
  {
    id: 'mock-8',
    title: 'Chronos Rift',
    backdrop_path: 'https://picsum.photos/seed/time/1920/1080',
    poster_path: 'https://picsum.photos/seed/time-p/500/750',
    overview: 'Time is a loop, and some loops are meant to be broken.',
    vote_average: 9.1,
    release_date: '2026-05-01',
    media_type: 'movie' as const,
    category: 'Action',
    views: 950000,
    trendingScore: 99
  },
  {
    id: 'mock-9',
    title: 'Shadow Runner',
    backdrop_path: 'https://picsum.photos/seed/runner/1920/1080',
    poster_path: 'https://picsum.photos/seed/runner-p/500/750',
    overview: 'The fastest courier in the megalopolis takes a job that might be his last.',
    vote_average: 8.2,
    release_date: '2025-09-10',
    media_type: 'tv' as const,
    category: 'Action',
    views: 1100000,
    trendingScore: 82
  },
  {
    id: 'mock-10',
    title: 'Starlight Odyssey',
    backdrop_path: 'https://picsum.photos/seed/star/1920/1080',
    poster_path: 'https://picsum.photos/seed/star-p/500/750',
    overview: 'The first manned mission to Andromeda encounters something unexpected.',
    vote_average: 9.3,
    release_date: '2026-06-20',
    media_type: 'movie' as const,
    category: 'Sci-Fi',
    views: 2500000,
    trendingScore: 94
  },
  {
    id: 'mock-11',
    title: 'Pixel Perfect',
    backdrop_path: 'https://picsum.photos/seed/pixel/1920/1080',
    poster_path: 'https://picsum.photos/seed/pixel-p/500/750',
    overview: 'An AI developer creates the perfect companion, but at what cost?',
    vote_average: 8.8,
    release_date: '2026-01-15',
    media_type: 'movie' as const,
    category: 'Drama',
    views: 700000,
    trendingScore: 88
  },
  {
    id: 'mock-12',
    title: 'Neon Pulse',
    backdrop_path: 'https://picsum.photos/seed/pulse/1920/1080',
    poster_path: 'https://picsum.photos/seed/pulse-p/500/750',
    overview: 'The music scene of the future is literally to die for.',
    vote_average: 8.5,
    release_date: '2025-10-05',
    media_type: 'tv' as const,
    category: 'Music',
    views: 550000,
    trendingScore: 80
  }
];

export const CATEGORY_MOCK_DATA: Record<string, any[]> = {
  upcoming: [
    { id: 'up-1', title: 'Mars Colony 2099', poster_path: 'https://picsum.photos/seed/mars/500/750', release_date: '2026-12-25', media_type: 'movie', vote_average: 0 },
    { id: 'up-2', title: 'The Silent Sea: Season 2', poster_path: 'https://picsum.photos/seed/sea/500/750', release_date: '2026-08-10', media_type: 'tv', vote_average: 0 },
    { id: 'up-3', title: 'Beyond the Horizon', poster_path: 'https://picsum.photos/seed/horizon/500/750', release_date: '2027-01-15', media_type: 'movie', vote_average: 0 },
  ],
  ongoing: [
    { id: 'on-1', title: 'Neon Pulse', poster_path: 'https://picsum.photos/seed/pulse/500/750', media_type: 'tv', vote_average: 8.5, status: 'ongoing' },
    { id: 'on-2', title: 'Shadow Runner', poster_path: 'https://picsum.photos/seed/runner/500/750', media_type: 'tv', vote_average: 7.9, status: 'ongoing' },
    { id: 'on-3', title: 'Glitch City', poster_path: 'https://picsum.photos/seed/glitch/500/750', media_type: 'tv', vote_average: 9.1, status: 'ongoing' },
  ],
  anime: [
    { id: 'an-1', title: 'Cyber Samurai', poster_path: 'https://picsum.photos/seed/samurai/500/750', media_type: 'tv', vote_average: 9.3, isAnime: true },
    { id: 'an-2', title: 'Spirit Bound', poster_path: 'https://picsum.photos/seed/spirit/500/750', media_type: 'movie', vote_average: 8.8, isAnime: true },
    { id: 'an-3', title: 'Void Walker', poster_path: 'https://picsum.photos/seed/void/500/750', media_type: 'tv', vote_average: 9.0, isAnime: true },
  ],
  action: [
    { id: 'ac-1', title: 'Velocity', poster_path: 'https://picsum.photos/seed/velocity/500/750', media_type: 'movie', vote_average: 7.5 },
    { id: 'ac-2', title: 'Iron Fist', poster_path: 'https://picsum.photos/seed/iron/500/750', media_type: 'movie', vote_average: 8.2 },
  ],
  romance: [
    { id: 'ro-1', title: 'Digital Hearts', poster_path: 'https://picsum.photos/seed/hearts/500/750', media_type: 'movie', vote_average: 8.4 },
    { id: 'ro-2', title: 'Signal Love', poster_path: 'https://picsum.photos/seed/signal-l/500/750', media_type: 'movie', vote_average: 7.8 },
  ],
  horror: [
    { id: 'ho-1', title: 'The Glitch', poster_path: 'https://picsum.photos/seed/glitch-h/500/750', media_type: 'movie', vote_average: 6.9 },
    { id: 'ho-2', title: 'Static', poster_path: 'https://picsum.photos/seed/static/500/750', media_type: 'movie', vote_average: 7.2 },
  ]
};

export const MOCK_CATEGORIES = [
  { title: 'Trending Now', movies: MOCK_MOVIES },
  { title: 'Action Packed', movies: [...MOCK_MOVIES].reverse() },
  { title: 'Sci-Fi Universe', movies: MOCK_MOVIES.slice(0, 3) },
  { title: 'Pakistani Cinema', movies: MOCK_MOVIES.slice(2, 5) },
  { title: 'Anime World', movies: MOCK_MOVIES }
];
